FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -i https://mirrors.aliyun.com/pypi/simple/ -r requirements.txt

# 假设 zh_core_web_sm-3.7.0.tar.gz 位于项目根目录下
COPY zh_core_web_sm-3.7.0.tar.gz ./

# 安装模型
RUN pip install --no-cache-dir zh_core_web_sm-3.7.0.tar.gz


COPY . .

EXPOSE 8000

CMD ["python", "backend/manage.py", "runserver", "0.0.0.0:8000"]

