FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt && \
    python -m spacy download zh_core_web_md && \
    python -m spacy download zh_core_web_sm

COPY . .

EXPOSE 8000

CMD ["python", "backend/manage.py", "runserver", "0.0.0.0:8000"]
# 假设已安装了 spaCy 库，在此基础上安装中文模型
